# Generated by Django 4.0.4 on 2022-05-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_is_lab'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('department', 'semester', 'subject', 'batch'), name='unique_class'),
        ),
    ]
