# Generated by Django 4.0.4 on 2022-06-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labexam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labexamquestion',
            name='question_number',
        ),
    ]
