# Generated by Django 4.0.4 on 2022-04-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('piston_lang', models.CharField(max_length=10)),
                ('editor_lang', models.CharField(max_length=10)),
                ('demo_code', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
