# Generated by Django 4.0.4 on 2022-05-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10, unique=True)),
                ('piston_lang', models.CharField(max_length=10, unique=True)),
                ('editor_lang', models.CharField(max_length=10, unique=True)),
                ('demo_code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('language', 'piston_lang', 'editor_lang'), name='unique_lang'),
        ),
    ]
