# Generated by Django 4.0.4 on 2022-04-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='editor_lang',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='piston_lang',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
