# Generated by Django 4.0.4 on 2022-05-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_language_editor_lang_alter_language_language_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('language', 'piston_lang', 'editor_lang'), name='unique_lang'),
        ),
    ]
