# Generated by Django 4.0.4 on 2022-05-05 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_language_unique_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question', models.TextField(blank=True, max_length=500)),
                ('answer', models.FileField(blank=True, null=True, upload_to='uploads/editor/correctanswer')),
                ('mark', models.IntegerField()),
                ('fullscreen', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editor.language')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('input_file', models.FileField(upload_to='uploads/editor/testcase/input')),
                ('output_file', models.FileField(upload_to='uploads/editor/testcase/output')),
                ('mark', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='editor.question')),
            ],
        ),
    ]
