# Generated by Django 4.0.3 on 2022-04-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='stream',
            field=models.CharField(choices=[('B.Tech', 'Btech'), ('M.Tech', 'Mtech')], default='B.Tech', max_length=8),
        ),
    ]
