# Generated by Django 4.0.3 on 2022-04-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_batch_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='stream',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech')], default='B.Tech', max_length=8),
        ),
    ]
