# Generated by Django 4.0.3 on 2022-04-24 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_teacher_classes'),
        ('base', '0003_alter_batch_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teacher'),
        ),
    ]
