# Generated by Django 4.0.3 on 2022-04-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_class_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='teacher',
            new_name='owner',
        ),
    ]
