# Generated by Django 4.0.3 on 2022-04-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_teacher_class_owner'),
        ('user', '0002_remove_teacher_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='base.class'),
        ),
    ]
