# Generated by Django 4.0.3 on 2022-04-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_subject_semester'),
        ('user', '0002_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.semester'),
        ),
    ]
