# Generated by Django 4.0.3 on 2022-04-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_student_department_teacher_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
