# Generated by Django 4.0.4 on 2022-05-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_unique_class'),
        ('user', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='students', to='classes.class'),
        ),
    ]
