# Generated by Django 4.0.4 on 2022-05-02 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resourcefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_files', to='resources.resource'),
        ),
    ]
