# Generated by Django 4.0.4 on 2022-05-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('resources', '0003_alter_resourcefile_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='class_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='classes.class'),
        ),
    ]
