# Generated by Django 4.0.4 on 2022-05-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('editor', '0002_alter_language_editor_lang_alter_language_language_and_more'),
        ('user', '0004_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField()),
                ('total_marks', models.IntegerField()),
                ('class_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_exps', to='classes.class')),
            ],
        ),
        migrations.CreateModel(
            name='LabQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question', models.TextField(blank=True, max_length=500)),
                ('answer', models.FileField(upload_to='uploads/lab/correctanswer')),
                ('mark', models.IntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='labs.labexperiment')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editor.language')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='uploads/lab/testcase/input')),
                ('output_file', models.FileField(upload_to='uploads/lab/testcase/output')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='labs.labquestion')),
            ],
        ),
        migrations.CreateModel(
            name='LabAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to='uploads/lab/studentanswer')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('execution_tries', models.IntegerField()),
                ('execution_time', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='labs.labquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
