# Generated by Django 4.0.4 on 2022-05-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabTestCases',
            new_name='LabTestCase',
        ),
    ]
