# Generated by Django 4.0.4 on 2022-05-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_labquestion_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='labanswer',
            constraint=models.UniqueConstraint(fields=('question', 'student'), name='unique_answer'),
        ),
    ]
