# Generated by Django 4.0.4 on 2022-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_rename_labtestcases_labtestcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labquestion',
            name='answer',
            field=models.FileField(null=True, upload_to='uploads/lab/correctanswer'),
        ),
    ]
