# Generated by Django 4.0.4 on 2022-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_labquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labquestion',
            name='answer',
            field=models.FileField(blank=True, null=True, upload_to='uploads/lab/correctanswer'),
        ),
    ]
