# Generated by Django 4.0.4 on 2022-05-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_labtestcase_tc_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='labanswer',
            name='unique_answer',
        ),
        migrations.AddConstraint(
            model_name='labanswer',
            constraint=models.UniqueConstraint(fields=('question', 'student'), name='unique_lab_answer'),
        ),
    ]
