# Generated by Django 4.0.4 on 2022-06-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_remove_labanswer_unique_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labquestion',
            name='question_number',
        ),
    ]
